### ISSUE TITLE
Usar Base64 para la interfaz de datos de entrada/salida y claves

### ISSUE THREAD

**Issue by agubelu** [AgoraUS-G1-1617/Verification#10]
Buenas:

Hemos hecho una prueba rápida de la primera versión del JAR de verificación, y por lo que hemos podido ver funciona a la perfección, por lo que sólo cabe agradeceros vuestro trabajo rápido y eficaz.

Quería plantear una sugerencia sobre el formato en el que se entregan los datos y las claves: dado que son un array de bytes, quizá sería más conveniente usar una codificación Base64 para los mismos, por lo que se entregaría una cadena de texto que es mucho más cómoda que la representación como cadena de un array de números. De hecho, es el formato estándar que se suele utilizar para el almacenamiento de claves.

Una solución muy simple sería implementar la codificación/decodificación de Base64 en el propio código de gestión de la línea de comandos, por lo que el funcionamiento interno de vuestra aplicación no sufriría cambios y seguiría trabajando con arrays de bytes. En este ejemplo se puede apreciar que Java incluye una librería para simplificar el proceso:

http://stackoverflow.com/questions/2418485/how-do-i-convert-a-byte-array-to-base64-in-java

De esta manera, tanto los datos de entrada/salida como las claves se gestionarían más facilmente por nuestra parte.

Un saludo.

**Comment by HernanGonzalez42** [comment]
Resuelto en 1fa674613faf73cf7ae410d4231858e32b8389d7
