### ISSUE TITLE
Eliminación de métodos heredados inútiles para el proyecto

### ISSUE THREAD

**Issue by AlejandroSanabria1** [AgoraUS-G1-1617/Verification#11]
El proyecto tiene muchos métodos heredados que no usaremos en nuestro caso.

Todos los métodos relacionados con MD5, DES o SHA deberán ser eliminados ya que solo usamos el método de encriptación RSA.

**Comment by AlejandroSanabria1** [comment]
Solucionados, esperando revisión del Jefe de proyecto.

**Comment by HernanGonzalez42** [comment]
Solucionado, queda el método checkVote pero lo conservaremos por si los del año que viene lo quieren usar
