### ISSUE TITLE
La mayoría de los tests heredados son triviales

### ISSUE THREAD

**Issue by HernanGonzalez42** [AgoraUS-G1-1617/Verification#2]
Casi el 100% de los métodos de testeo jUnit heredados consisten en verificar que las salidas de los métodos funcionales sean not Null, sin validar el propio contenido de la salida. Es necesario implementar tests más eficaces y exigentes.

**Comment by HernanGonzalez42** [comment]
@AlejandroSanabriaUS los tests están bien, pero en su mayoría muestran errores por System.out en lugar de detectarlos con asserts. Esto es problemático porque dificultan su automatización. Hace falta añadir más asserts y más estrictos, no solo assertNotNull.

**Comment by AlejandroSanabria1** [comment]
Leído, cambiaré los test añadiéndoles los asserts que faltan.

**Comment by AlejandroSanabria1** [comment]
Tenemos que corregir los errores en los test que se han producido al cambiar los métodos.
