### ISSUE TITLE
Interfaz de línea de comandos

### ISSUE THREAD

**Issue by HernanGonzalez42** [AgoraUS-G1-1617/Verification#3]
Es necesario implementar un método `main(String[] args)` que sirva de interfaz entre el .jar y los subsistemas que lo consuman. Previamente, hay que definir, acordar y documentar con dichos subsistemas la sintaxis de comandos que se usará. Por ejemplo:
`./verificacion help` para mostrar la lista de comandos posibles,
`./verificacion encode` para cifrar un voto, etc.

**Comment by agubelu** [comment]
En un principio, los métodos que necesitaríamos por línea de comandos desde recuento son:

- Generación de un par de claves pública/privada (ambas generadas y devueltas a la vez)
- Encriptar un dato dada una clave pública
- Desencriptar un dato dada una clave privada

A ser posible, que la salida sea también por consola (System.out) para que podamos capturarla y procesarla.

**Comment by ManuelLR** [comment]
pregunta, ¿no sería más cómodo usar el jar como una librería?

**Comment by HernanGonzalez42** [comment]
Lo es, pero Recuento (@agubelu) usa Node.js y por lo que me han dicho pueden ejecutar el jar en linea de comandos con parámetros, pero no consumirlo directamente.
Según los de cabina, hay una librería de python que les sirve para comunicarse con un jar, pero no se si es por comandos o consumiéndola directamente, así que me dirán cómo va la cosa cuando lo averigüen, supongo.
@agubelu : roger that, implementaremos esa funcionalidad 👍

**Comment by ManuelLR** [comment]
perfecto, sabéis que por el tema de integración no habrá mucho problema. 
Ya me contareis la solución definitiva

**Comment by agubelu** [comment]
@ManuelLR La solución en principio es esa, lógicamente siempre y cuando nuestro container tenga java, que supongo que lo tendrá.

**Comment by ManuelLR** [comment]
cada uno busca un container y lo usa pero siempre podéis crear uno personalizado que además tenga java (openjdk u oracle)

**Comment by HernanGonzalez42** [comment]
Ambas cabinas de votaciones consumirán nuestro .jar desde la línea de comandos, de modo que no es necesario más que ese punto de acceso.
