### ISSUE TITLE
Despliegue e integración automatizados

### ISSUE THREAD

**Issue by HernanGonzalez42** [AgoraUS-G1-1617/Verification#6]
En la medida de lo posible, se busca que en cuanto compilemos una nueva versión estable desde la rama master, ésta se cargue en internet de forma que los demás subsistemas tengan acceso fluido y automático a la versión más reciente de la librería. Manolo nos puede dar más detalles.

**Comment by ManuelLR** [comment]
este es el tema de integración continua. Cuando consigáis aclarar que hace vuestro módulo y como se usa, como dice @HernanGonzalez42, poneos en contacto conmigo para el tema e integración
