### ISSUE TITLE
Las claves generadas en KeyGen no se pueden acceder

### ISSUE THREAD

**Issue by HernanGonzalez42** [AgoraUS-G1-1617/Verification#7]
Lo métodos de KeyGen producen un KeyPair. Se pueden obtener objetos PublicKey y PrivateKey con .getPublic() y .getPrivate(), pero el valor de esos objetos no es accesible directamente. Eso dificulta que los subsistemas que consumen Verificación puedan extraerlas del jar para almacenarlas por sí mismos, para luego reintroducirlas cuando llamen. Posible solución: crear clases hijas de PublicKey y PrivateKey que implementen toString() en forma de expresión regular, y que puedan parsear esas mismas Strings generadas para construir objetos de su clase correspondiente.

**Comment by HernanGonzalez42** [comment]
Resuelto, solo falta que alguien compruebe los cambios de  9d4c8cae5b04079dc823ba40afaf8481e724644d y 1d3f6a9ccc16be5a155baf675bba3acb02259887 para verificar que la issue está acabada.

**Comment by ghost** [comment]
He comprobado los cambios y los tests se ejecutan sin problemas.

**Comment by HernanGonzalez42** [comment]
Las claves se convierten bien internamente, pero dan problemas a la hora de ser impresas o leídas en la consola.

**Comment by HernanGonzalez42** [comment]
Solucionado, se representan como array de bytes "[valor,...,valor]".
