### ISSUE TITLE
Tamaño de las claves RSA

### ISSUE THREAD

**Issue by agubelu** [AgoraUS-G1-1617/Verification#9]
Hola:

¿Hay algún motivo concreto por el que las claves RSA sean de 512 bits? Hoy en día lo habitual es usar 2048 bits, un tamaño inferior se puede considerar inseguro.

Un saludo.

**Comment by HernanGonzalez42** [comment]
Pues no lo hay, lo hemos heredado asi y no nos dimos cuenta, lo cambiaremos en un momento, gracias por avisar :)
